### ISSUE TITLE
Add Developing Reactive Streams with Spring vs Quarkus to Publications

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkusio.github.io#1049]
```
- id: 6DevelopingReactiveStreamswithSpringvsQuarkusYouTube-2021-07-06
  type: video 
  title: "Developing Reactive Streams with Spring vs Quarkus"
  date: "2021-07-06"
  author: "Daniel Oh"
  note: "Developing Reactive Streams with Spring vs Quarkus"
  url: "https://www.youtube.com/watch?v=MKvIMqP3KDk"
  urldate: "2021-07-06"

```

**Comment by gastaldi** [comment]
@jclingan I think it would be much easier if you added that snippet directly to a PR instead (in https://github.com/quarkusio/quarkusio.github.io/blob/develop/_data/publications.yaml). 

I can see there are several issues with the same snippet format piling up

**Comment by maxandersen** [comment]
Closed by fetchpub as detected to already be included.
