### ISSUE TITLE
Page is broken on Windows - IE 11

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkusio.github.io#111]
Page is broken on Windows - IE 11

Tried from macOS via VirtualBox virtual machine with Windows Server 2016
Example:

<img width="1391" alt="screenshot 2019-03-07 at 11 05 18" src="https://user-images.githubusercontent.com/925259/53948726-c2f53f00-40c8-11e9-9d82-aec83b3e4522.png">

On the get started page there are more problems when you scroll down a bit. Also the footer is broken on IE 11. The main page has problems too.

**Comment by rsvoboda** [comment]
I asked my wife to check the site on Windows 10 + Edge browser and it looks ok.
So only IE 11 is the trouble maker.

**Comment by maxandersen** [comment]
For context analytics says that in last 24 hours  0.71% of users was Internet Explorer 11, which was even outnumbered by Opera so I would not consider this an issue.

Especially since the page is otherwise fully functional.

**Comment by maxandersen** [comment]
worse is that code.quarkus.io is completely black so opened issue there.
