### ISSUE TITLE
Building on OpenShift fails due to location of Dockerfile

### ISSUE THREAD

**Issue by jamesfalkner** [quarkusio/quarkusio.github.io#116]
This may be related to #66 but this is specific to OpenShift - since the `Dockerfile` isn't in the root of the project directory (after following the getting started guide for native image), when I issue

```
oc start-build quarkus-quickstart --from-dir=. --follow
```
It fails since OpenShift can't find the `Dockerfile`. If I first `cp src/main/docker/Dockerfile .` then run the build, it works as OpenShift is looking for the Dockerfile to be in the root of the binary image uploaded to it. I see no way to override this.

**Comment by cescoffier** [comment]
Isn't an option to indicate the Dockerfile location? 
Initially, the dockerfile was at the root, but we decided to move to its own directory.
If it's not possible to indicate the file location, we should update the guide to copy the file at the root of the directory.

**Comment by cescoffier** [comment]
Instructions must be updated.

BTW, there is a funky way:
```
oc new-build --strategy=docker . -D - <./src/main/docker/Dockerfile
oc start-build centos --from-dir=.
```

**Comment by cescoffier** [comment]
There is a PR on the Quarkus repository fixing this issue.
