### ISSUE TITLE
Community page not showing images

### ISSUE THREAD

**Issue by jonathanvila** [quarkusio/quarkusio.github.io#1251]
### Describe the bug

Community page not showing images on quarkus website

![image](https://user-images.githubusercontent.com/1836434/144591467-ea89e007-2bff-48d7-bdf2-f34df5fa2576.png)

### Expected behavior

showing images

### Actual behavior

not showing images

### How to Reproduce?

https://quarkus.io/community/

**Comment by gsmet** [comment]
@insectengine could you have a look at this one? If the page is not supposed to be there anymore, we should probably redirect somewhere?

**Comment by insectengine** [comment]
@gsmet - The page is deprecated. We should redirect it to the github discussions main page.
@maxandersen  - thoughts?

**Comment by maxandersen** [comment]
Makes sense @insectengine

**Comment by gsmet** [comment]
Has been resolved.
