### ISSUE TITLE
Blog post about "how to write a quarkus extension"

### ISSUE THREAD

**Issue by bennetelli** [quarkusio/quarkusio.github.io#1278]
Hi there,

we at Red Hat Insights created a Quarkus extension (quarkus-logging-cloudwatch) and published it on the Quarkiverse and I thought it could be helpful for others to read something about it. 
Things like "what needs to be done to get the extension in quarkiverse? What are the benefits of Quarkiverse? What is needed to create a Quarkus extension?" and so on.

Would you be interested in my blog post?

**Comment by bennetelli** [comment]
here's the PR https://github.com/quarkusio/quarkusio.github.io/pull/1282

**Comment by jclingan** [comment]
Older article. Closing.

**Comment by jclingan** [comment]
Whups, my bad. Reopening

**Comment by bennetelli** [comment]
All good @jclingan :) I published the article already :) we can close this issue
