### ISSUE TITLE
HTTPS on https://www.quarkus.io/ is broken (invalid cert)

### ISSUE THREAD

**Issue by zsmuller** [quarkusio/quarkusio.github.io#130]
I've just found out about Quarkus in the post at https://www.infoworld.com/article/3356839/red-hat-s-quarkus-aims-to-modernize-java-apps.amp.html. They provided a link to https://www.quarkus.io/. The browser showed an error (about the certificate) instead of the actual site.

www.quarkus.io is an alias (CNAME) for quarkus.io and the latter points to the same IP list as pages.github.com (which is an alias for github.github.io).

However www.quarkus.io and quarkus.io seem to land in different virtualhost configs, because the former is served with the cert of GitHub (i.e. subject's CN is "www.github.com", the SAN list is "www.github.com,*.github.io,*.githubusercontent.com,*.github.com,github.com,github.io,githubusercontent.com"), while the latter is served with a cert for the right domain (i.e. both subject's CN and the SAN list contain the "quarkus.io" domain).

If I force my http client to accept the cert, then www.quarkus.io redirects to quarkus.io and all is well. However the initial SSL CN/SAN mismatch is still at least unpleasant to visitors.

I've no idea whether sites on GitHub Pages can be set up so this doesn't happen or is this maybe a limitation of GitHub Pages itself? :o

**Comment by gsmet** [comment]
This is a GitHub thing unfortunately. We can't do anything about it.
