### ISSUE TITLE
Gem install jekyll redundant in README

### ISSUE THREAD

**Issue by gekorob** [quarkusio/quarkusio.github.io#132]
Hi all,
  maybe installing explicitly the Jekyll gem like reported in README can be redundant, cause Jekyll is already a dependency in the Gemfile and is installed by the bundle command.

I suggest to change the line, if for you is ok

```
gem install jekyll bundler
```

with the line

```
gem install bundler
```

**Comment by maxandersen** [comment]
I noticed that too but forgot about it :) Now fixed - thanks for reporting.
