### ISSUE TITLE
hibernate-orm-guide confusing about properties in {config-file}

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkusio.github.io#143]
This part first says that some props should be added to `{config-file}` and then it says that they "are not the same ones as made available in `{config-file}`". What is this supposed to mean @gsmet or @adelasofia ?

https://github.com/quarkusio/quarkusio.github.io/blame/develop/_guides/hibernate-orm-guide.adoc#L42-L57

**Comment by gsmet** [comment]
You're right, it's confusing, will be fixed in next release.
