### ISSUE TITLE
Building Native Image Guide - distroless link is broker

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkusio.github.io#144]
On the Building Native Image Guide, the link to the distroless image is broken.

It links to https://github.com/quarkusio/quarkus/tree/master/docker/distroless but should linkes to 
https://github.com/quarkusio/quarkus-images/tree/graalvm-1.0.0-rc14/distroless

**Comment by gzaronikas** [comment]
@loicmathieu I hit that too, sent pr #145 for fixing that.

**Comment by cescoffier** [comment]
My fault, I moved the image, forgot the link.

**Comment by gsmet** [comment]
This has been fixed a while ago.
