### ISSUE TITLE
registry.quarkus.io/maven  404

### ISSUE THREAD

**Issue by ccpatrut** [quarkusio/quarkusio.github.io#1490]
**Describe the bug**

Hi guys 

It looks to me that your registry: 
https://registry.quarkus.io/maven 

returns always 404. 

Is this actually normal? We were trying to set it up with our internal mirroring system as described in https://quarkus.io/guides/extension-registry-user always thinking something blocks our requests but actually the page was all along returning NOT_FOUND.

Could you please have a look on it? 

**Which pages**
https://quarkus.io/guides/extension-registry-user

**Comment by maxandersen** [comment]
@gastaldi and @aloubyansky

**Comment by gastaldi** [comment]
@ccpatrut this is correct, it is not a usual browsable maven repository, but an API exposed as a Maven repository to be used solely by our tooling CLI

**Comment by maxandersen** [comment]
before we close - @ccpatrut what mirroring system are you using that is haaving problems with 404's ?

**Comment by gsmet** [comment]
No response, closing.
