### ISSUE TITLE
The page, USING THE EVENT BUS, references a non-existent method - sendAndForget.

### ISSUE THREAD

**Issue by cgruver** [quarkusio/quarkusio.github.io#1516]
## Affected Page:

[https://quarkus.io/guides/reactive-event-bus#sending-messages](https://quarkus.io/guides/reactive-event-bus#sending-messages)

## Issue:

```java
// Case 1
bus.sendAndForget("greeting", name)
// Case 2
bus.publish("greeting", name)
// Case 3
Uni<String> response = bus.<String>request("address", "hello, how are you?")
        .onItem().transform(Message::body);
```

`io.vertx.mutiny.core.eventbus.EventBus` does not have a `sendAndForget` method.

I suspect that `io.vertx.mutiny.core.eventbus.EventBus.send(...)` is the relevant method.  And that it becomes fire-and-forget if the listener is a `void` method.  But...  I'm just learning this...  so...  I'm ready to be wrong.  ;-)

**Comment by gsmet** [comment]
Was fixed in the main repo.
