### ISSUE TITLE
Merge Panache Guides

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkusio.github.io#155]
I guess the Panache guides could be streamlined and cleaned from repetition. 
Right now there are two guides:

https://quarkus.io/guides/hibernate-orm-panache-guide
and: https://quarkus.io/guides/hibernate-orm-guide.html#setting-up-and-configuring-hibernate-orm-without-persistence-xml-recommended

**Comment by gsmet** [comment]
No. It's different: you can use Hibernate ORM in Quarkus without the Panache layer. So there might be some redundancy but it's not exactly the same goal.

**Comment by FroMage** [comment]
Yeah, the idea behind the Hibernate ORM with Panache guide is to build on the Hibernate ORM guide. I don't think it repeats too much information either, unless you have specific things to point out?
