### ISSUE TITLE
JWT Properties typo

### ISSUE THREAD

**Issue by richsanram** [quarkusio/quarkusio.github.io#156]
https://quarkus.io/guides/jwt-guide

In the configuration properties section, the name of 3 properties are bad, with an extra "L"

quarkus.smalllrye-jwt.enabled
quarkus.smalllrye-jwt.realm-name
quarkus.smalllrye-jwt.auth-mechanism

While the correct properties are:

quarkus.smallrye-jwt.enabled
quarkus.smallrye-jwt.realm-name
quarkus.smallrye-jwt.auth-mechanism

**Comment by starksm64** [comment]
Thanks for the report. This has been addressed in the main projects docs since that is where the content comes from.
https://github.com/quarkusio/quarkus/pull/1776

**Comment by gsmet** [comment]
Fixed a while ago.
