### ISSUE TITLE
add rss feed links

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkusio.github.io#1561]
Suggested in https://twitter.com/preslavrachev/status/1584517283690745856.

add RSS links on quarkus.io/insights

video feed: https://feeds.listenbox.app/rss/9w4VBtq9s1v/video.rss
audio feed: https://feeds.listenbox.app/rss/9w4VBtq9s1v/audio.rss

**Comment by insectengine** [comment]
https://github.com/quarkusio/quarkusio.github.io/pull/1571
