### ISSUE TITLE
Broken link for Quarkus guide: Using Security with JPA

### ISSUE THREAD

**Issue by nielspardon** [quarkusio/quarkusio.github.io#1564]
### Describe the bug

When navigating to `https://quarkus.io/guides/sec` clicking on the tile for `Using Security with JPA` leads to an error 404.

### Expected behavior

The link should lead to the actual guide for using security with JPA :-) 

### Actual behavior

Seems the adoc file has been renamed and the tiles on the Quarkus guides site have not been updated accordingly.

### Additional information

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/10451444/199046400-c17df311-ce01-4dbe-80bc-f0efd78de3a4.png">

**Comment by sberyozkin** [comment]
Hi @nielspardon Thanks for spotting it, I've just transferred this issue to the website project.
FYI, the `security-jpa` guide has been refactored to represent a Getting Started with Quarkus Security guide, but as far as the website is concerned, I guess it makes sense to keep the existing card/tile and link to a new doc, let me do it
