### ISSUE TITLE
Fix alignment of primary navigation (logo and hamburger icon)

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkusio.github.io#1618]
The logo and "hamburger" more icon have vertical alignment issues on smaller screen sizes.

**Comment by holly-cummins** [comment]
I can look at this.

**Comment by holly-cummins** [comment]
The two elements are currently aligned at the top:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/11509290/214591033-0286d70e-2ac0-4e82-90d1-a5805757f35d.png">

(This isn't that exciting, I was just impressed by my improvised on-screen ruler.)
