### ISSUE TITLE
Inconsistency with the build native guide and code output snippet

### ISSUE THREAD

**Issue by nmcl** [quarkusio/quarkusio.github.io#172]
In https://quarkus.io/guides/building-native-image-guide.html after "To see the NativeGreetingResourceIT run against the native executable, runs ./mvnw verify -Pnative:" there's a snippet of output but it's not consistent with what I see, which is below ...

[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< org.acme:getting-started >----------------------
[INFO] Building getting-started 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.sun.xml.bind:jaxb-osgi:jar:2.2.10 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ getting-started ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ getting-started ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ getting-started ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/marklittle/github/scratch/quarkus/native/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ getting-started ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ getting-started ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.quickstart.GreetingResourceTest
2019-04-11 16:11:19,283 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-04-11 16:11:21,863 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 2580ms
2019-04-11 16:11:22,811 INFO  [io.quarkus] (main) Quarkus 0.13.1 started in 0.920s. Listening on: http://[::]:8081
2019-04-11 16:11:22,811 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.821 s - in org.acme.quickstart.GreetingResourceTest
2019-04-11 16:11:26,685 INFO  [io.quarkus] (main) Quarkus stopped in 0.015s
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ getting-started ---
[INFO] Building jar: /Users/marklittle/github/scratch/quarkus/native/target/getting-started-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:0.13.1:build (default) @ getting-started ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Alpha4
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1698ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: /Users/marklittle/github/scratch/quarkus/native/target/getting-started-1.0-SNAPSHOT-runner.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:0.13.1:native-image (default) @ getting-started ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on Java HotSpot(TM) 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /usr/local/graalvm-ee-1.0.0-rc15/Contents/Home/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar getting-started-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[getting-started-1.0-SNAPSHOT-runner:76838]    classlist:   8,451.75 ms
[getting-started-1.0-SNAPSHOT-runner:76838]        (cap):   5,543.67 ms
[getting-started-1.0-SNAPSHOT-runner:76838]        setup:   8,989.39 ms
16:11:58,573 INFO  [org.xnio] XNIO version 3.7.0.Final
16:11:59,243 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.0.Final
16:12:05,456 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Alpha4
[getting-started-1.0-SNAPSHOT-runner:76838]   (typeflow):  27,781.54 ms
[getting-started-1.0-SNAPSHOT-runner:76838]    (objects):  22,437.03 ms
[getting-started-1.0-SNAPSHOT-runner:76838]   (features):   1,486.11 ms
[getting-started-1.0-SNAPSHOT-runner:76838]     analysis:  53,014.64 ms
Printing call tree to /Users/marklittle/github/scratch/quarkus/native/target/reports/call_tree_getting-started-1.0-SNAPSHOT-runner_20190411_161247.txt
Printing list of used classes to /Users/marklittle/github/scratch/quarkus/native/target/reports/used_classes_getting-started-1.0-SNAPSHOT-runner_20190411_161252.txt
Printing list of used packages to /Users/marklittle/github/scratch/quarkus/native/target/reports/used_packages_getting-started-1.0-SNAPSHOT-runner_20190411_161252.txt
[getting-started-1.0-SNAPSHOT-runner:76838]     universe:   1,093.40 ms
[getting-started-1.0-SNAPSHOT-runner:76838]      (parse):   5,007.98 ms
[getting-started-1.0-SNAPSHOT-runner:76838]     (inline):   7,960.32 ms
[getting-started-1.0-SNAPSHOT-runner:76838]    (compile):  82,269.20 ms
[getting-started-1.0-SNAPSHOT-runner:76838]      compile: 100,142.43 ms
[getting-started-1.0-SNAPSHOT-runner:76838]        image:   8,368.34 ms
[getting-started-1.0-SNAPSHOT-runner:76838]        write:   3,281.87 ms
[getting-started-1.0-SNAPSHOT-runner:76838]      [total]: 191,770.38 ms
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.0:integration-test (default) @ getting-started ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.quickstart.NativeGreetingResourceIT
Executing [/Users/marklittle/github/scratch/quarkus/native/target/getting-started-1.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
2019-04-11 16:14:49,453 INFO  [io.quarkus] (main) Quarkus 0.13.1 started in 0.028s. Listening on: http://[::]:8081
2019-04-11 16:14:49,463 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.132 s - in org.acme.quickstart.NativeGreetingResourceIT
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.0:verify (default) @ getting-started ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:45 min
[INFO] Finished at: 2019-04-11T16:14:54-04:00
[INFO] ------------------------------------------------------------------------

Specifically this piece on the web page:

[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.081 s - in org.acme.quickstart.GreetingResourceIT
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

Doesn't match.

**Comment by gsmet** [comment]
Are you using the output of the https://quarkus.io/guides/getting-started-guide to try the native one?

Because, if not, that would explain your issue with the rest endpoint not being available and the fact that you have only 1 test here.

It's stated at the beginning of the guide: `This guide takes as input the application developed in the Getting Started Guide.`.

Thanks for clarifying.

**Comment by gsmet** [comment]
Closing as outdated.
