### ISSUE TITLE
Wrong boolean value in Quarkus Analytics property example

### ISSUE THREAD

**Issue by tomperr** [quarkusio/quarkusio.github.io#1736]
**Describe the bug**

I think the last sentence on the `Quarkus Usage Analytics` page is wrong:
https://github.com/quarkusio/quarkusio.github.io/blob/fe46373b21251161a3345be2f5de2210d3d936d7/usage.md?plain=1#L45-L53

If I understand it correctly, we need to set the value do `false` to enable it, so it would be:
```
Similarly, you can set it to `quarkus.analytics.disabled=false` if you want to enable it for a single run.
```

**Which pages**

[Quarkus Usage Analytics](https://quarkus.io/usage/)

**Comment by gefloh** [comment]
Stumbled over this today too, yes. I opened a to correct it.
