### ISSUE TITLE
Blank page for https://es.quarkus.io/guides/

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkusio.github.io#1791]
I notice that while some pages on the https://es.quarkus.io site work, https://es.quarkus.io/guides/ is a blank page for me, in Firefox, Chrome, and Safari. There's nothing obvious in the console. The cn.quarkus and ja.quarkus versions work fine.

**Comment by gian1200** [comment]
Looks fixed 
![image](https://github.com/user-attachments/assets/e2bdee66-7b9d-4faa-98f1-899149e3fd51)

**Comment by holly-cummins** [comment]
Thanks for checking, @gian1200! Closing.
