### ISSUE TITLE
Some guide documents title are not refrected to quarkus.io site

### ISSUE THREAD

**Issue by ynojima** [quarkusio/quarkusio.github.io#1794]
**Describe the bug**

Some guide documents title are not refrected to quarkus.io site.
It seems the wrong title is taken form the source file name.

**Which pages**

- Sample1:
https://quarkus.io/guides/getting-started-dev-services
In its source(https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/getting-started-dev-services.adoc#your-second-quarkus-application), the title is "Your second Quarkus application", but the website is rendered as "Getting Started Dev Services".
- Sample2:
https://quarkus.io/guides/upx
In its souce(https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/upx.adoc#compressing-native-executables-using-upx), the title is "Compressing native executables using UPX", but the website is rendered as "Upx".

**Comment by gsmet** [comment]
Fixing that is easy: empty new lines in the headers need to be removed. 
I already fixed the getting started dev services one except if I’m mistaken.

**Comment by gsmet** [comment]
I'm preparing a PR for the main repo, this will be fixed soon.

**Comment by gsmet** [comment]
Thanks for the detailed report btw!

**Comment by gsmet** [comment]
Fixed upstream in https://github.com/quarkusio/quarkus/pull/36274
