### ISSUE TITLE
Asciidoc directive is not closed in prerequisites.adoc

### ISSUE THREAD

**Issue by ynojima** [quarkusio/quarkusio.github.io#1795]
**Describe the bug**

`ifdef::prerequisites-ide[{prerequisites-ide}]` is not closed.
It should be closed with a corresponding `endif::[]` directive.

**Which pages**
https://github.com/quarkusio/quarkus/blob/3.4.1/docs/src/main/asciidoc/_includes/prerequisites.adoc?plain=1#L10
https://github.com/quarkusio/quarkusio.github.io/blob/develop/_versions/2.7/guides/includes/devtools/prerequisites.adoc?plain=1#L10
https://github.com/quarkusio/quarkusio.github.io/blob/develop/_versions/2.13/guides/_includes/prerequisites.adoc?plain=1#L10
https://github.com/quarkusio/quarkusio.github.io/blob/develop/_versions/2.16/guides/_includes/prerequisites.adoc?plain=1#L10
https://github.com/quarkusio/quarkusio.github.io/blob/develop/_versions/3.2/guides/_includes/prerequisites.adoc?plain=1#L10

I'm not sure where the close directive be placed.

**Comment by gsmet** [comment]
This is actually valid AsciiDoctor: see `Example 3. ifdef single line example` in https://docs.asciidoctor.org/asciidoc/latest/directives/ifdef-ifndef/ .

**Comment by ynojima** [comment]
My apologies for misunderstanding.

**Comment by gsmet** [comment]
No worries. I actually had to check in the doc why I did that :)
