### ISSUE TITLE
Many security keywords are not effective in finding guides

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkusio.github.io#1800]
**Describe the bug**

In the list from https://github.com/quarkusio/quarkusio.github.io/blob/develop/_data/guides-latest.yaml#L397C9-L397C9 only `security`, `oidc` and `oauth2` are effective in finding some security guides, `sso` does not work for any marked security guide, and none of `github,google,microsoft,apple,facebook,twitter,spotify` is also effective

**Which pages**
For example, typing `twitter` in the `Filter by keyword` text field should find https://quarkus.io/guides/security-openid-connect-providers

**Comment by sberyozkin** [comment]
I wonder if it is because I've only updated the latest yaml doc but the main also should be updated ?

**Comment by gsmet** [comment]
I wouldn't be surprised if keyword search was lost when the new guides index was put in place. Not sure though.

There is a plan to have a far better search engine soon so probably a good idea to wait for this project to materialize.

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/36302 will address it and give the recipe for adding more keywords if necessary.
