### ISSUE TITLE
Enhance Quarkus Docs page with Dark mode

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkusio.github.io#1809]
### Description

As stated in the title, to enable a Dark mode option for the docs page. Nothing fancy nor complicated, but focusing on readability.

OS sync for initial configuration would be a nice to have thing, but not necessary.

Current docs:
https://quarkus.io/guides/cache
![image](https://github.com/quarkusio/quarkus/assets/405347/9c959ebf-2ac4-476b-a0ae-f1caa171b5db)

### Implementation ideas

Maybe something similar to GitHub's Dark dimmed: grey (non black background and non white text).

GitHub:
![image](https://github.com/quarkusio/quarkus/assets/405347/9b5641c7-a806-41d0-9b8b-74d9580f8b50)

I know colors are a preference and relative, but if some people like a darker (or lighter) mode, maybe it can be expanded to:

- Lighter (whiter or current)
- Light (current or darker current)
- Dark (grey)
- Darker (black)

**Comment by gsmet** [comment]
I moved the issue to the website project. /cc @insectengine this might be a good idea. If I'm not mistaken @jponge had fun with this for the Mutiny website: https://smallrye.io/smallrye-mutiny/2.5.1/ .

**Comment by jponge** [comment]
Mutiny uses [MkDocs Material](https://squidfunk.github.io/mkdocs-material/) so the dark mode was built-in and I _just_ had to choose colors 🤣

**Comment by holly-cummins** [comment]
Watching this for http://extensions.quarkus.io and http://docs.quarkiverse.io, too.

**Comment by insectengine** [comment]
Put this on my work queue to look at but will need to prioritize.

This would need to be a site wide thing (not just on docs) so it will be a larger lift.

**Comment by roby2014** [comment]
Bump, need this.

**Comment by The-Funk** [comment]
I get the occasional light induced migraines so dark mode is enabled on my machine everywhere I can find it. Glad to see someone already put in this request.

**Comment by insectengine** [comment]
I submitted a draft PR with a dark mode for the site. It's a clean approach that detects the user's OS settings and sets either light or dark mode. I didn't include a switcher to avoid extra javascript and visual clutter on the page. 

https://github.com/quarkusio/quarkusio.github.io/pull/1908

Note" While I've created dark mode versions of images on the content pages, we'll have to sort out how to swap images in the documentation to have dark mode friendly images via ascidoc.

@gsmet @maxandersen @holly-cummins

**Comment by maxandersen** [comment]
@holly-cummins @insectengine remind me where we landed on this? my memory is broken :)

**Comment by insectengine** [comment]
https://github.com/quarkusio/quarkusio.github.io/pull/1962

^ This PR addresses the outstanding issues.

1. Added color mode switcher in navigation (that changes to show state: light, dark, system).
2. Fixed pre code color issue in darkmode
3. Added solution for images in blog/guides with transparency in dark mode.

Outstanding issue: Still need Guides index fix for icons in dark mode
@yrodiere @ia3andy  < How is the image swap working for the main guides page going?

**Comment by yrodiere** [comment]
> @yrodiere @ia3andy < How is the image swap working for the main guides page going?

@marko-bekhta ^

**Comment by marko-bekhta** [comment]
Just double checked it and the build with https://github.com/quarkusio/search.quarkus.io/issues/241 is in production. The guides layout is updated and the guide icons will be of the main text color:
```css
.qs-guide-icon svg {
    width: 70px;
    margin: 1rem 0px 0px;
    fill: var(--main-text-color);
}
```

**Comment by insectengine** [comment]
@maxandersen  - the change above removes the last known blocker.

**Comment by yrodiere** [comment]
@gsmet @insectengine Are you sure this change is complete? It seems configuration tables were overlooked... ?

![image](https://github.com/quarkusio/quarkusio.github.io/assets/412878/9118f4e0-61e0-42ae-a917-392325427d9a)

https://quarkus.io/guides/building-native-image#configuration-reference

**Comment by marko-bekhta** [comment]
Noticed a slight mismatch in the tooltip label and actual theme switch sequence: 
![theme-switch](https://github.com/quarkusio/quarkusio.github.io/assets/4004823/96de9b06-032f-4e70-99b2-ebb32cd31fac)
`next:` in the tooltip doesn't match the theme the button actually switches to 🙈

**Comment by The-Funk** [comment]
@insectengine thank you for your work on this. 🎉
