### ISSUE TITLE
Following guide security-oidc-bearer-token-authentication-tutorial, dev ui missing url.

### ISSUE THREAD

**Issue by Mert18** [quarkusio/quarkusio.github.io#1838]
**Describe the bug**

https://quarkus.io/guides/security-oidc-bearer-token-authentication-tutorial#:~:text=Open%20a%20Dev%20UI%2C%20which%20you%20can%20find%20at%20/q/dev%2Dv1%2C%20then%20click%20a%20Provider%3A%20Keycloak%20link%20in%20an%20OpenID%20Connect%20Dev%20UI%20card. in this line, the DEV UI is linked as "q/dev-v1" but I was unable to find the DEV UI here. The dev ui was running on "q/dev-ui" instead. Should we correct it or did I make a mistake following the guide?

**Which pages**
https://quarkus.io/guides/security-oidc-bearer-token-authentication-tutorial

**Comment by phillip-kruger** [comment]
That is a mistake, that was the old Dev UI and it should change to /q/dev-ui.

**Comment by maxandersen** [comment]
this was already merged. thus closing.
