### ISSUE TITLE
Update website to new logo

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkusio.github.io#184]

**Comment by rsvoboda** [comment]
Seems like fixed via 
 - https://github.com/quarkusio/quarkusio.github.io/commit/194a5fe291b7d2cea4b9b5a22ace24663a3fd564
 - https://github.com/quarkusio/quarkusio.github.io/commit/63398d0939ffd2cbb267fffefc691d5f0eef045a

@emmanuelbernard @jkbrock @adelasofia can it be closed ?

**Comment by emmanuelbernard** [comment]
Right, I've created the follow up color alignment one though https://github.com/quarkusio/quarkusio.github.io/issues/197

**Comment by rsvoboda** [comment]
Favicon needs update too - https://github.com/quarkusio/quarkusio.github.io/issues/199
