### ISSUE TITLE
Error in kubernetes-guide in Deploying the application in OpenShift

### ISSUE THREAD

**Issue by myron-randall** [quarkusio/quarkusio.github.io#185]
When executing the second command from the section Deploying the application in OpenShift
in the kubernetes-guide I am receiving the following error:

quarkus-quickstarts\getting-started>oc new-build --binary
--name=quarkus-quickstart -l app=quarkus-quickstart
    * A Docker build using binary input will be created
      * The resulting image will be pushed to image stream tag "quarkus-quicksta
rt:latest"
      * A binary build was created, use 'start-build --from-dir' to trigger a ne
w build

--> Creating resources with label app=quarkus-quickstart ...
    imagestream.image.openshift.io "quarkus-quickstart" created
    buildconfig.build.openshift.io "quarkus-quickstart" created
--> Success

quarkus-quickstarts\getting-started>oc patch bc/quarkus-qu
ickstart -p '{"spec":{"strategy":{"dockerStrategy":{"dockerfilePath":"src/main/d
ocker/Dockerfile.native"}}}}'
**Error from server (BadRequest): json: cannot unmarshal string into Go value of t
ype map[string]interface {}**

Running on OCP: 
oc v3.11.59
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

openshift v3.11.59
kubernetes v1.11.0+d4cacc0

**Comment by gsmet** [comment]
@geoand any chance you could take a look at that one? Or find someone who can?

Or @cescoffier ?

**Comment by geoand** [comment]
@gsmet Sure thing. I'll be able to take a look in a few hours.

**Comment by geoand** [comment]
@myron-randall I tried the guide and it worked just fine (against OCP 3.11 no less). Is there anything else you can tell us about your environment?

**Comment by myron-randall** [comment]
I am running oc from a Windows 7 client. Our Openshift installation is a local install (private cloud). It is managed by another organization in our company.

**Comment by geoand** [comment]
Would it be possible for you to test against a Minishift cluster as well?

**Comment by myron-randall** [comment]
I tried it on minishift from my Windows 10 machine and receive the same error.
oc patch bc/quarkus-quickstart -p '{"spec":{"strategy":{"dockerStrategy":{"dockerfilePath":"src/main/docker/Dockerfile.native"}}}}'
Error from server (BadRequest): json: cannot unmarshal string into Go value of type map[string]interface {}

oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://192.168.99.109:8443
kubernetes v1.11.0+d4cacc0

**Comment by geoand** [comment]
@myron-randall can you please try your `oc patch ...` by adding `-v 9` (this is most verbose possible output)?

**Comment by myron-randall** [comment]
Here is the otuput from the OCP instance:
oc patch bc/quarkus-qu
ickstart -p '{"spec":{"strategy":{"dockerStrategy":{"dockerfilePath":"src/main/d
ocker/Dockerfile.native"}}}}' -v 9
I0531 09:54:10.166307   21092 loader.go:359] Config loaded from file C:\Users\mr
andall/.kube/config
I0531 09:54:10.169307   21092 loader.go:359] Config loaded from file C:\Users\mr
andall/.kube/config
I0531 09:54:10.182307   21092 loader.go:359] Config loaded from file C:\Users\mr
andall/.kube/config
I0531 09:54:10.183307   21092 round_trippers.go:386] curl -k -v -XGET  -H "Accep
t: application/json" -H "User-Agent: oc/v1.11.0+d4cacc0 (windows/amd64) kubernet
es/d4cacc0" -H "Authorization: Bearer 9A7fhVIry14sf7zQVCCa7-ov8uL58Uz8t_w-FG3eun
Y" 'https://console.tools.adp.allianz:443/apis/build.openshift.io/v1/namespaces/
agcs-ea-apps/buildconfigs/quarkus-quickstart'
I0531 09:54:11.027307   21092 round_trippers.go:405] GET https://console.tools.a
dp.allianz:443/apis/build.openshift.io/v1/namespaces/agcs-ea-apps/buildconfigs/q
uarkus-quickstart 200 OK in 844 milliseconds
I0531 09:54:11.028307   21092 round_trippers.go:411] Response Headers:
I0531 09:54:11.028307   21092 round_trippers.go:414]     Cache-Control: no-store

I0531 09:54:11.028307   21092 round_trippers.go:414]     Content-Type: applicati
on/json
I0531 09:54:11.028307   21092 round_trippers.go:414]     X-Frame-Options: sameor
igin
I0531 09:54:11.028307   21092 round_trippers.go:414]     Audit-Id: a6040585-ab5e
-4a7d-861a-e4c9e199d292
I0531 09:54:11.028307   21092 round_trippers.go:414]     Content-Length: 917
I0531 09:54:11.028307   21092 round_trippers.go:414]     X-Xss-Protection: 1
I0531 09:54:11.028307   21092 round_trippers.go:414]     X-Content-Type-Options:
 nosniff
I0531 09:54:11.028307   21092 round_trippers.go:414]     Strict-Transport-Securi
ty: max-age=31536000
I0531 09:54:11.028307   21092 round_trippers.go:414]     Date: Fri, 31 May 2019
16:54:10 GMT
I0531 09:54:11.028307   21092 request.go:897] Response Body: {"kind":"BuildConfi
g","apiVersion":"build.openshift.io/v1","metadata":{"name":"quarkus-quickstart",
"namespace":"agcs-ea-apps","selfLink":"/apis/build.openshift.io/v1/namespaces/ag
cs-ea-apps/buildconfigs/quarkus-quickstart","uid":"9e6ac4a2-83c4-11e9-a301-00505
6885d84","resourceVersion":"758542965","creationTimestamp":"2019-05-31T16:53:30Z
","labels":{"app":"quarkus-quickstart"},"annotations":{"openshift.io/generated-b
y":"OpenShiftNewBuild"}},"spec":{"triggers":[{"type":"GitHub","github":{"secret"
:"jMI4jk25kcsENv4vMDYD"}},{"type":"Generic","generic":{"secret":"zVISLkxvuMb4QSt
ld8Pk"}}],"runPolicy":"Serial","source":{"type":"Binary","binary":{}},"strategy"
:{"type":"Docker","dockerStrategy":{}},"output":{"to":{"kind":"ImageStreamTag","
name":"quarkus-quickstart:latest"}},"resources":{},"postCommit":{},"nodeSelector
":null,"successfulBuildsHistoryLimit":5,"failedBuildsHistoryLimit":5},"status":{
"lastVersion":0}}
I0531 09:54:11.030307   21092 loader.go:359] Config loaded from file C:\Users\mr
andall/.kube/config
I0531 09:54:11.031307   21092 request.go:897] Request Body: "{spec:{strategy:{do
ckerStrategy:{dockerfilePath:src/main/docker/Dockerfile.native}}}}"
I0531 09:54:11.031307   21092 round_trippers.go:386] curl -k -v -XPATCH  -H "Acc
ept: application/json" -H "Content-Type: application/strategic-merge-patch+json"
 -H "User-Agent: oc/v1.11.0+d4cacc0 (windows/amd64) kubernetes/d4cacc0" -H "Auth
orization: Bearer 9A7fhVIry14sf7zQVCCa7-ov8uL58Uz8t_w-FG3eunY" 'https://console.
tools.adp.allianz:443/apis/build.openshift.io/v1/namespaces/agcs-ea-apps/buildco
nfigs/quarkus-quickstart'
I0531 09:54:11.231307   21092 round_trippers.go:405] PATCH https://console.tools
.adp.allianz:443/apis/build.openshift.io/v1/namespaces/agcs-ea-apps/buildconfigs
/quarkus-quickstart 400 Bad Request in 200 milliseconds
I0531 09:54:11.231307   21092 round_trippers.go:411] Response Headers:
I0531 09:54:11.231307   21092 round_trippers.go:414]     X-Content-Type-Options:
 nosniff
I0531 09:54:11.231307   21092 round_trippers.go:414]     Strict-Transport-Securi
ty: max-age=31536000
I0531 09:54:11.231307   21092 round_trippers.go:414]     Cache-Control: no-store

I0531 09:54:11.231307   21092 round_trippers.go:414]     Content-Length: 190
I0531 09:54:11.231307   21092 round_trippers.go:414]     Date: Fri, 31 May 2019
16:54:11 GMT
I0531 09:54:11.232307   21092 round_trippers.go:414]     X-Frame-Options: sameor
igin
I0531 09:54:11.232307   21092 round_trippers.go:414]     X-Xss-Protection: 1
I0531 09:54:11.232307   21092 round_trippers.go:414]     Audit-Id: e2521e91-a388
-4c96-bcf9-315b3a5c29e3
I0531 09:54:11.232307   21092 round_trippers.go:414]     Content-Type: applicati
on/json
I0531 09:54:11.232307   21092 request.go:897] Response Body: {"kind":"Status","a
piVersion":"v1","metadata":{},"status":"Failure","message":"json: cannot unmarsh
al string into Go value of type map[string]interface {}","reason":"BadRequest","
code":400}
I0531 09:54:11.232307   21092 helpers.go:201] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "json: cannot unmarshal string into Go value of type map[string]int
erface {}",
  "reason": "BadRequest",
  "code": 400
}]
F0531 09:54:11.233307   21092 helpers.go:119] Error from server (BadRequest): js
on: cannot unmarshal string into Go value of type map[string]interface {}

**Comment by geoand** [comment]
Something tells me this might have to do with the windows terminal.... Can you please try something similar to https://github.com/minishift/minishift/issues/1273#issuecomment-323127597 @myron-randall ?

**Comment by myron-randall** [comment]
Yes, that appears to be the issue: The following command quoted and escaped works!
 oc patch bc/quarkus-quickstart -p "{\"spec\":{\"strategy\":{\"dockerStrategy\":{\"dockerfilePath\":\"src/main/docker/Dockerfile.native\"}}}}"

**Comment by geoand** [comment]
Would you like to submit a PR to the Quarkus main docs with this command for Windows?

If you don't have the time to do so, I can do it as well.

**Comment by myron-randall** [comment]
I may have spoken too soon. I am now getting an error on the start build:
oc start-build quarkus-quickstart --from-dir=. --follow

Step 4/9 : COPY target/*-runner /work/application
error: build error: No source files were specified

**Comment by geoand** [comment]
@myron-randall You first need to have built the native binary using one of the methods mentioned in the "building-native-image-guide" (which is mentioned as a prerequisite to this guide).

I am going to go ahead and close this issue since I believe it is resolved. If you think otherwise, feel free to reopen.
