### ISSUE TITLE
[Quarkus guides] configuration property table is obscured by table of content

### ISSUE THREAD

**Issue by Dieken** [quarkusio/quarkusio.github.io#1900]
### Describe the bug

https://quarkus.io/guides/kafka

The horizontal scrollbar isn't shown, it's very inconvenient to check the configuration property table:

<img width="1725" alt="image" src="https://github.com/quarkusio/quarkus/assets/2365/5aaed461-6a81-4337-9645-ccaa43d61f23">

**Comment by Dieken** [comment]
> > It's better to minimize the table of content to a menu button on the top right.
> 
> This first issue isn't fixed by the PR above. I suggest removing sticky style from the table of content as a quick fix.
> 
> https://purecss.io/menus/#responsive-menus-that-hide For your reference.

Second commit in the PR fixed the first issue,  the TOC is moved back to left, so that wide table can overflow to the right.

Notice the second commit depends on the first commit,  the "display" style of tables can't be "block".

**Comment by insectengine** [comment]
The all config page looks good but the TOC page is problematic.

Moving the TOC to the left side of the page forces the larger tables to break the page on the right side. This causes a the page to horizontally scroll past the header.

![brokenheader](https://github.com/quarkusio/quarkusio.github.io/assets/928656/98d5c499-31c7-453e-ab2f-9426a45444ee)

**Comment by insectengine** [comment]
I've submitted a PR to address to address this issue.

https://github.com/quarkusio/quarkusio.github.io/pull/1903

I'd suggest we add a shadow method to indicate to the user when there is additional content in a table that is accessed through scrolling. This appears on the side that has more hidden content (left or right). To make this work, I removed the light blue alternating background from the rows.

Code source: https://codepen.io/ramiro-ruiz/pen/YzKVOGK

![Screenshot 2024-02-27 at 5 41 22 PM](https://github.com/quarkusio/quarkusio.github.io/assets/928656/bc5fd56e-d664-497d-be9f-e872a17c0938)

**Comment by Dieken** [comment]
Yes, the table is overflowing out of the grid, a bit ugly but much more usable, I wouldn’t like to scroll forth and back to read the whole table rows even my screen is wide enough.

It’s more ideal to turn the toc into a sticky menu button, show/hide or expand/collapse the toc, so that the content can occupy whole grid like before when the toc is hidden.

I will withdraw the second commit, let’s fix the issue of all-config table asap, thanks!

**Comment by Dieken** [comment]
> I've submitted a PR to address to address this issue.
> 
> #1903
> 
> I'd suggest we add a shadow method to indicate to ...
> @gsmet


I see that PR was merged, that's better, but I feel that only sets up a warning flag above a manhole on road, not to cover it safely.

Please double consider its usability, thanks!

**Comment by yrodiere** [comment]
@insectengine Is this issue supposed to be fixed?

I just had a look and it seems that we still have the same problem as before, even with your patch merged:

![image](https://github.com/quarkusio/quarkusio.github.io/assets/412878/5515bf79-40f9-474a-abaf-b7e806b861b7)

**Comment by insectengine** [comment]
@yrodiere - Looking into this but those long code names are wreaking havoc on tables as cells are the width of the longest one. Hide/show the TOC won't fix having massive tables with long content that wont wrap. I'm working on finding out why this doesn't have horizontal scroll.

Perhaps there is a more layout friendly way to display content with these super long code elements minimize edge cases?

<img width="1508" alt="Screenshot 2024-05-01 at 3 18 32 PM" src="https://github.com/quarkusio/quarkusio.github.io/assets/928656/fcf0afcb-4fc7-4a0e-a761-7ae657d5f855">
<img width="1492" alt="Screenshot 2024-05-01 at 3 18 40 PM" src="https://github.com/quarkusio/quarkusio.github.io/assets/928656/2050e6c7-9256-4d90-befc-86016c799e17">

**Comment by yrodiere** [comment]
@insectengine True. I'd suggest whoever adjusts the Kafka documentation to use the same structure as configuration properties. It doesn't overflow, even if configuration property keys are absurdly long like in Hibernate Search:

![image](https://github.com/quarkusio/quarkusio.github.io/assets/412878/49683cda-4546-4dfe-8d6f-7ff297a43201)

That being said, the layout could also be more wide-screen-friendly -- on my screen there's more than enough width to display this table, if we were to remove the margins on the left and right hand side. See:

![Screenshot from 2024-05-02 09-02-53](https://github.com/quarkusio/quarkusio.github.io/assets/412878/b5bb0828-c650-4fa9-8c7e-cb5cbf69ba5a)

Something like this would allow more content width and still be perfectly fine IMO:

![Screenshot from 2024-05-02 09-02-53 - suggestion](https://github.com/quarkusio/quarkusio.github.io/assets/412878/17fa7d86-9aa1-4267-99a1-56a23bc3699a)


This doesn't change the fact it must still work on narrower screens, of course.

**Comment by insectengine** [comment]
<img width="922" alt="Screenshot 2024-05-02 at 4 59 27 PM" src="https://github.com/quarkusio/quarkusio.github.io/assets/928656/ec05f8bb-a591-4f18-b08a-6755f5974867">

The text now folds neatly so the table fits on the page. No need for the shadow treatment for horizontal scroll.
