### ISSUE TITLE
3.8 guide url

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkusio.github.io#1907]
**Describe the bug**
we have https://quarkus.io/version/3.2/guides/*, now with LTS 3.8 we should have https://quarkus.io/version/3.8/*

**Comment by tqvarnst** [comment]
+1. https://quarkus.io/guides should be the latest, but if you want to link to content in the current version these may be invalid or the content has changed. It would be good also to have the versioned link for the latest.

**Comment by someth2say** [comment]
Adding some context here:

When writing technical docs, sometimes we need to link to specific versions of the documentation.
If the version we are targeting to is an "old" (meaning not the latest) LTS, we can easily use `https://quarkus.io/version/<version>/guides/` (p.e. https://quarkus.io/version/3.2/guides/)
But if the versions we target to is the "current" LTS,  `https://quarkus.io/version/<version>/guides/` is not available.

Guides for latest LTS versions are available as `https://quarkus.io/guides`. But this link is mutable: the moment a new LTS comes, it will move to the new version; hence it is not usable for linking to the current version, but only to the latest version.

**Comment by ebramirez** [comment]
Looks like this is already solved.

**Comment by gsmet** [comment]
Yes, I pushed it with 3.8.2 and it is now part of the updated release process so should be done automatically from now on (for LTS versions).
