### ISSUE TITLE
Permalink for docs search results

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkusio.github.io#1917]
**Describe the bug**
The current search in Docs does not allow for the user to share the domain for the search results as the URL for the page doesn't change with search filtering. 

**Which pages**
https://quarkus.io/guides/

**Comment by holly-cummins** [comment]
Ideally we should be able to add query parameters to the URL, and then read them on load. In my experience doing so can sometimes cause infinite loops if state/actions/calls/updates aren't managed carefully, but that's not an insoluble technical problem, just a thing to watch out for on implementation.

**Comment by yrodiere** [comment]
@ia3andy I think this would have to be implemented on the search.quarkus.io webcomponents, no? Would it be hard?

**Comment by yrodiere** [comment]
Deploying the fix to prod as part of https://github.com/quarkusio/search.quarkus.io/pull/259 ; will be effective on the next deployment of quarkus.io.
