### ISSUE TITLE
Illegible colour scheme in the code snippets

### ISSUE THREAD

**Issue by meridsa** [quarkusio/quarkusio.github.io#1950]
# Description

The code snippets are challenging to read. I am unsure how much I am uncommonly affected due to red-green colourblindness, but I feel that both comments (gray text on gray background), as well as the annotation and property (orange-on-gray) are difficult to read. I have also checked with the [silktide plugin](https://chromewebstore.google.com/detail/silktide-accessibility-ch/mpobacholfblmnpnfbiomjkecoojakah) for these colours

# Show issue

## annotation text (i.e. "/service" text)
![image](https://github.com/quarkusio/quarkusio.github.io/assets/35993351/851bf373-1681-4279-8e10-4cff913dd89d)

## Comments
![image](https://github.com/quarkusio/quarkusio.github.io/assets/35993351/9ba084af-fc48-4af1-a68a-b65944bc20ff)

# Scope

Affects all code snippets on all pages.

**Comment by gsmet** [comment]
This is probably a bug in the dark mode introduced yesterday. @insectengine could you have a look soon? It seems very problematic.

**Comment by meridsa** [comment]
I changed to dark-mode to be able to read:

![image](https://github.com/quarkusio/quarkusio.github.io/assets/35993351/ad5a35ba-c190-41b5-a6a5-0483fe8ac927)
