### ISSUE TITLE
Switch 'developer-facing' branch to be called 'main'

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkusio.github.io#1952]
We can adjust the github settings to publish from another branch, say 'pages'. 

This would reduce some friction for developers maintaining this site, by using a more conventional branch name for daily work.

**Comment by maxandersen** [comment]
here is my 4 year old vote for it https://groups.google.com/g/quarkus-dev/c/oyfQ8ougPVU/m/5EL83FH7BgAJ

I don't grok why main/master is required for github pages - I never used that but didn't push for it then.

**Comment by holly-cummins** [comment]
> I don't grok why main/master is required for github pages - I never used that but didn't push for it then.

I wonder if it used to be necessary, and now isn't, because they made it configurable in the UI? But certainly using it now just causes confusion, IMO. 

The following steps will be needed, but someone with admin privileges like @gsmet will need to do them. The first three need to be done at around the same time, and then the last two can be done more leisurely. I did this a while ago for another site and I *think* I've got the optimum order. 

- Do the swapping of branches, so that `master` gets renamed to `gh-pages` and `develop` gets renamed to `main`
- Update the github pages config in the project settings so that it publishes from `gh-pages`
- Update the docs and workflows; I've raised https://github.com/quarkusio/quarkusio.github.io/pull/1961 for this
- Update the project settings so that `main` is the default branch
- Socialise the change to contributors, although it should be an easy rebase and low impact. I expect some, like me, already rebase onto `main` by accident and then have to re-rebase onto `develop`, so this will save them a step

**Comment by gsmet** [comment]
Not saying we shouldn't do this but we also have to update https://github.com/quarkusio/quarkus/blob/main/docs/sync-web-site.sh#L40-L44 in all maintained branches.

**Comment by holly-cummins** [comment]
> Not saying we shouldn't do this but we also have to update https://github.com/quarkusio/quarkus/blob/main/docs/sync-web-site.sh#L40-L44 in all maintained branches.

Ah, yes. I'd just looked at `.github/workflows/sync-main-doc.yml` and assumed it was all done by a pull from this repo. 

I think we can make the `quarkusio` changes asynchronously (and in advance), though. We should just be able to drop `-b develop` from that command, and it will continue to clone the default branch. When we switch the name of the default branch, the clone will continue to work.

**Comment by gsmet** [comment]
I will coordinate the changes as `I think` is not sufficient in the release process, even if I think I agree with you :).

I'll get it done by end of week.

**Comment by holly-cummins** [comment]
> I will coordinate the changes as `I think` is not sufficient in the release process, even if I think I agree with you :).

I'm hoping I'm right, because removing knowledge of the branch structure of the `quarkusio.github.io` repo from the `quarkusio` branches would be a (v minor) good thing to do, independent of this particular rename. But I agree that one shouldn't base one's entire online presence on hope. 🤣

> I'll get it done by end of week.

🎉

**Comment by yrodiere** [comment]
@gsmet Please note this will likely break indexing in search.quarkus.io, we need to coordinate to get it updated right when you make the change.
cc @marko-bekhta

**Comment by marko-bekhta** [comment]
> Will it affect localization repos too?

https://github.com/doc-l10n-kit/quarkus-l10n-utils/blob/1a8e427a011a6dce91ad6fd4f4408a2de45808c1/bin/sync-submodule#L16

looks like it 🙈

**Comment by ynojima** [comment]
Thank you for let me know.
I'll update the script once the rename is implemented.

**Comment by gsmet** [comment]
I said `end of week` three weeks ago and here we are at the end of `a` week. I did it today as it's a slow day and wanted to make sure things wouldn't be too bad if it broke things completely. I'm monitoring the first deployment.

@ynojima the `develop` branch has been renamed `main` so please take it into account in the localization repos. Thanks!

**Comment by ynojima** [comment]
Thank you for pinging me. I made pull-requests to each localization repositories to address the branch name change.

**Comment by gsmet** [comment]
@ynojima thanks!

**Comment by holly-cummins** [comment]
I think this can be closed. I just used ctrl-r to do `git fetch upstream && git rebase upstream/main`, and it was delightful.
