### ISSUE TITLE
Improve ToC for guides

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkusio.github.io#196]
Quoting @mkouba 

But to be honest, we should add some styles to the TOC on the website (something like "float:left;") because the TOC is sometimes too long and the guide does not read well.

**Comment by gsmet** [comment]
An example we already have: https://quarkus.io/guides/extension-authors-guide .

If we can get it to look nice, we should probably add a TOC on all the guides.

**Comment by mkouba** [comment]
There is https://github.com/quarkusio/quarkus/issues/1490 already :-)

**Comment by gsmet** [comment]
I have fixed it a while ago.
