### ISSUE TITLE
Should we have some light-mode content on the front page?

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkusio.github.io#1980]
If I'm on http://quarkus.io and I change the dark mode toggle, nothing on the page changes. That's consistent with the design, but it makes it look like the toggle isn't working. I wonder if something on the page should be light mode, so that users get visual feedback on the toggle? (I got confused and thought I'd broken something because I had a sun image and dark content, but it was just that the whole page is always dark.)

cc @insectengine

**Comment by insectengine** [comment]
This is an artifact of the original move from a dark website to a light website. There was concern of the change could potentially be off putting for the users so as a compromise in keeping the home page. At this point, I'd say we scrap this approach and make light /dark versions of the home page that works like the rest of the site.

**Comment by insectengine** [comment]
[Resolves this ](https://github.com/quarkusio/quarkusio.github.io/pull/1983)
