### ISSUE TITLE
Update https://quarkus.io/favicon.ico to reflect new logo

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkusio.github.io#199]
Update https://quarkus.io/favicon.ico to reflect new logo

GH location: https://github.com/quarkusio/quarkusio.github.io/blob/develop/favicon.ico

**Comment by emmanuelbernard** [comment]
I've updated it but did a crappy job of taking the png 32x32, adding a white background and converting it to .ico
In particular, @jkbrock will know if the removal of the alpha and if using the white vs reverse logo is preferred and adapt.

**Comment by jkbrock** [comment]
@emmanuelbernard I have a hybrid solution that should account for the light/dark theme problem. 0 Alpha on the outside, white or black on the inside - submitting with the black version because it makes the logo slightly more visible.
