### ISSUE TITLE
404 page not dark-theme compatible

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkusio.github.io#2027]
The 404 page is not compatible with the dark theme: only the font color is changed and the contrast is not good enough.

Go there with the dark theme: https://quarkus.io/totoz

**Comment by holly-cummins** [comment]
This inspired me to check on the extensions subsite (for example, https://quarkus.io/extensions/totoz). The layout isn't brilliant, but it's ok for dark mode.
 
<img width="1433" alt="image" src="https://github.com/quarkusio/quarkusio.github.io/assets/11509290/d311e088-e658-49c7-afb0-2b8a6d7d0cb7">

(That's independent of anything done on this issue, just noting it down so we know I checked. :) )
