### ISSUE TITLE
Datasource Guide: Includes in _guides/datasource-guide.adoc are broken.

### ISSUE THREAD

**Issue by leandrosilvaferreira** [quarkusio/quarkusio.github.io#203]
The includes in page who reference configuration properties of agroal are broken.

They reference to ../../../../extensions/agroal/deployment/src/test/java/io/quarkus/agroal/test/... wich would be in https://github.com/quarkusio/quarkus/tree/master/extensions/agroal/deployment/src/test/resources which is not visible as a parent project.

How you guys think is the best way to solve this ?

**Comment by gsmet** [comment]
Argh, totally missed that.

I think for now, we have to refrain from using includes.

@LightGuard could you take care of it? I'll resynchronize the guides.

**Comment by LightGuard** [comment]
I'll figure out the proper fix.

**Comment by gsmet** [comment]
We got rid of the includes for now. Let's close this one and revisit with includes at some point.
