### ISSUE TITLE
show more auto collapses making copying hard

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkusio.github.io#2044]
from zulip @galderz reported:
"I was trying to copy something that was shown in https://quarkus.io/guides/container-image after clicking on "Show more" and after selecting the text, the text section goes back to showing less. This is annoying since you can't see if the text is still selected...etc. Who takes care of this UI?"

I can reproduce it on osx firefox and chrome.

see recording

https://github.com/user-attachments/assets/2202227c-588b-4fa6-89cd-180c09498879

**Comment by insectengine** [comment]
Ah ok, wasn't following.

This is the default action off the config table as created in adoc. The entire row is clickable to make the hide/show function (not just the "show more" link). There is the icon on the right for copying code, but apparently folks don't like/or notice it.

I still question the need for this content to even have a hide/show feature as the bulk of the content is very short. 

I'll look into if we can reasonably modify the default.

**Comment by insectengine** [comment]
Worked with @ebullient  to make a fix.

https://github.com/quarkusio/quarkus/pull/41959

**Comment by galderz** [comment]
> This is the default action off the config table as created in adoc. The entire row is clickable to make the hide/show function (not just the "show more" link). There is the icon on the right for copying code, but apparently folks don't like/or notice it.

Oh I didn't notice the copy icon, but that only copies the environment variable name? I was trying to copy the configuration option explanation.
