### ISSUE TITLE
Guides all return 404's

### ISSUE THREAD

**Issue by jamesfalkner** [quarkusio/quarkusio.github.io#205]
at https://quarkus.io/guides/

All of the links on the left result in a 404...

**Comment by gsmet** [comment]
Looking into it. It works locally.

**Comment by gsmet** [comment]
It seems to be a GitHub related issue.

`https://quarkus.io/guides/application-configuration-guide` is automatically rewritten to `https://quarkus.io/guides/application-configuration-guide/` with a trailing `/`.

**Comment by gsmet** [comment]
We could probably rewrite the links to use the `.html` extension. That would probably prevent the rewriting... but in any case, all the existing links will be broken...

**Comment by gsmet** [comment]
It seems to be fixed. Apparently, it was just a transient error.

@jamesfalkner do you confirm?

**Comment by jamesfalkner** [comment]
Confirmed!
