### ISSUE TITLE
Links on `https://quarkus.io/usage/` are wrong

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkusio.github.io#2093]
**Describe the bug**

Links from the following section are wrong:

> ...adoption into sites like [extensions.quarkus.io](https://quarkus.io/usage/extensions.quarkus.io) and [code.quarkus.io](https://quarkus.io/usage/code.quarkus.io).

**Which pages**
https://quarkus.io/usage/

**Comment by holly-cummins** [comment]
Good spot, thanks!
