### ISSUE TITLE
Consider renaming blog to news

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkusio.github.io#215]
Today we named the link to the blog as "Blog" in the top menu. I think we did mention at some point to use "News" instead. WDYT @jkbrock ?
Then should we rename the links as well `/blog` to `/news` (which will break some links) unless we create redirect pages

**Comment by jkbrock** [comment]
This is a good suggestion and is being added to our upstream template for all projects. "News" will be reflected in the new forthcoming design.

**Comment by jkbrock** [comment]
Added to the mockup: https://xd.adobe.com/view/873a5241-8d88-4c7c-7eb7-5d05360e89f9-f10b

If approved we can push this one live quickly.

**Comment by emmanuelbernard** [comment]
While discussing it recently, there were people pushing against News and for keeping Blog because not every blog entry is about news. If you feel strongly otherwise, please add a comment here. I was the original person proposing that and I don't have a strong argument.
