### ISSUE TITLE
Copy/pasting code with callouts does not work properly

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkusio.github.io#220]
While the callouts themselves are not pasted, the comment signs are.

In the case of Java code, it's just annoying. In the case of a property file, it becomes a real issue.

See previous issue:
https://github.com/quarkusio/quarkusio.github.io/issues/99
https://github.com/quarkusio/quarkusio.github.io/issues/146

**Comment by rquinio** [comment]
I've opened https://github.com/asciidoctor/asciidoctor/issues/3346 upstream.

Example of page with the issue: https://quarkus.io/guides/kafka-guide#the-price-generator (https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/kafka-guide.adoc#the-price-generator)

Meanwhile I'd propose to:
- not use comments in front of callouts in code blocks (`// <1>` or `# <1>` => `<1>`). This is what some page already do (ex: https://quarkus.io/guides/cdi-reference / https://raw.githubusercontent.com/quarkusio/quarkusio.github.io/develop/_guides/cdi-reference.adoc). The comments are only strictly needed when including an actual executable source file. 
- remove `:icons: font` attribute override in few pages like https://quarkus.io/guides/getting-started-guide (https://raw.githubusercontent.com/quarkusio/quarkusio.github.io/develop/_guides/getting-started-guide.adoc), which workarounds the comments problem, but makes admonitions invisible (you can't see if it's a Note, Tip or Warning). :icons: attribute should be global.
