### ISSUE TITLE
Image of fedora-minimal version is incorrect

### ISSUE THREAD

**Issue by 16yuki0702** [quarkusio/quarkusio.github.io#225]
From this page.
https://quarkus.io/guides/building-native-image-guide.html

I just copied code and run, got error like below.

#code
```
FROM registry.fedoraproject.org/fedora-minimal
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

#command
```
$docker build -f src/main/docker/Dockerfile.native -t quarkus-quickstart/getting-started .
$docker run -i --rm -p 8080:8080 quarkus-quickstart/getting-started
./application: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```

I think this problem is occured from 
https://fedoraproject.org/wiki/Changes/FullyRemoveDeprecatedAndUnsafeFunctionsFromLibcrypt

From fedora 30, libcrypt.so.1 was renamed to libcrypt.so.2.
So I think we need to specify fedora-minimal version to 29 to not use latest version. 
```
FROM registry.fedoraproject.org/fedora-minimal:29
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```
I modied like this and run, command succeeded.
```
$ docker run -i --rm -p 8080:8080 quarkus-quickstart/getting-started
2019-06-14 07:54:24,322 INFO  [io.quarkus] (main) Quarkus 0.16.1 started in 0.009s. Listening on: http://0.0.0.0:8080
2019-06-14 07:54:24,322 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```

**Comment by emmanuelbernard** [comment]
Thanks for your patch, the source is actually this file https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/building-native-image-guide.adoc
And the problem you have found has been fixed there.
