### ISSUE TITLE
kogito directory link for quickstarts is dead

### ISSUE THREAD

**Issue by thescouser89** [quarkusio/quarkusio.github.io#235]
Hi,

From: https://quarkus.io/guides/kogito-guide (or: https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/kogito-guide.adoc), the following link in the text:

```
The solution is located in the using-kogito directory
```
for 'directory' is dead. There are no references to kogito in the quickstarts repository.

**Comment by gsmet** [comment]
Oh, this is embarrassing.

@mariofusco could you assemble a quickstart from the instructions in the guide and push a PR to the quickstarts repo?

Thanks!

**Comment by mariofusco** [comment]
@gsmet sorry about this. I guess @mswiderski is working on it. I'll meet him in person tomorrow and I'll work with him on this.

**Comment by mswiderski** [comment]
Here it is https://github.com/quarkusio/quarkus-quickstarts/pull/230 sorry for the delay was away for a week and since PRs for quickstarts must be for development branch was not able to do it from mobile device

**Comment by mswiderski** [comment]
@gsmet any feedback on the quickstart?

**Comment by thescouser89** [comment]
I wonder though, since it looks like we have a dead link detector, why didn't it catch this?

Thank you guys for getting the quickstarts so fast! You guys rock!!! :)

**Comment by kmacedovarela** [comment]
Hi all, I also noticed the `README` in this PR is missing the Kogito project. I understand the hurry on this release process, but I don't know the best way to contribute to it atm.  Here's a suggestion for the text. Feel free to improve it or change it in any way. 

* [Using Kogito](./using-kogito): A business application with Kogito capable of natively executing business assets (i.e. business processes and drools rules). 

Regards :)

**Comment by gsmet** [comment]
This one has been fixed.
