### ISSUE TITLE
Keep a decent security policy while allowing trackers

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkusio.github.io#237]
https://observatory.mozilla.org/analyze/quarkus.io
is good but in the process, I broke web site tracking
The initial grade was F (which means failing).

Here is what I did https://github.com/quarkusio/quarkusio.github.io/compare/060f7451b0c959d49280b4f47c6d89ff8a022e1d...57e8bd6e1d5305bf556e976b7a121fdcc84c4bc9

Please check console warning  / errors on Firefox and Chrome.

**Comment by gsmet** [comment]
I think this is fixed now.
