### ISSUE TITLE
Get Started Step 1 - You need an IDE Should List Java IDEs Instead of Going to IDE Wikipedia Page

### ISSUE THREAD

**Issue by danielhelfand** [quarkusio/quarkusio.github.io#240]
As part of the getting started information, it would be more helpful to list specific Java IDEs that might be helpful instead of linking to a general Wikipedia page on IDEs for all languages.

The source in question is [here](https://github.com/quarkusio/quarkusio.github.io/blob/15009263af366d392044032dcb1c1a5cdb26685d/_includes/get-started-band.html#L5). Simply changing the link to https://en.wikipedia.org/wiki/Comparison_of_integrated_development_environments#Java would be more helpful, but it might be better to be a little more particular about recommendations or find a better list than what's on Wikipedia.

**Comment by danielhelfand** [comment]
For the time being, I have updated the link to https://en.wikipedia.org/wiki/Comparison_of_integrated_development_environments#Java, but I'm wondering if there are better suggestions than this list or if general there are better ideas for what to link this to.

**Comment by emmanuelbernard** [comment]
Thanks @danielhelfand I was in this area and did an overhaul. Let me know.

**Comment by danielhelfand** [comment]
@emmanuelbernard Appreciate it for this and #244. It's a lot more understandable with better information but still has brevity to it. Nice work!
