### ISSUE TITLE
Warning About OpenJDK 12 for Step 2 of QUARKUS - GET STARTED

### ISSUE THREAD

**Issue by danielhelfand** [quarkusio/quarkusio.github.io#244]
Quarkus [does not support OpenJDK 12](https://github.com/quarkusio/quarkus/issues/1534) at this time, but it's an option after clicking on the link for `You need JDK 8+` as shown [here](https://adoptopenjdk.net/).

It would be helpful to provide some type of warning to only download OpenJDK 8 or 11 at this time to help others avoid the issue above.

**Comment by emmanuelbernard** [comment]
Fixed it in an overall.
