### ISSUE TITLE
Incomplete changelog in Quarkus 0.19.1 release post 

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkusio.github.io#251]
The [Quarkus 0.19.1 release post](https://quarkus.io/blog/quarkus-0-19.1-released/) contains a link to https://github.com/quarkusio/quarkus/releases/tag/0.19.0 which does not include the 0.19.1 commits.

Ping @gsmet

**Comment by gsmet** [comment]
Right, there was really nothing fancy so I didn't want to advertise it too much but, as you noticed it, I pushed an update, including a link.

Thanks for checking!
