### ISSUE TITLE
Blog misbehave in case of slug collision

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkusio.github.io#257]
The blog entries are in the form of `yyyy-mm-dd-slug.adoc` but are rendered as `/blog/slug/`

I just tested and when two blog entries share the same slug (e.g. `2019-01-01-foo.adoc` and `2019-05-10-foo.adoc`), the /blog/ page is rendered correctly but one of the two blogs is erased by the other. I've seen that the latest is rendered but that might not be deterministic.

We need a solution as it will become more likely in the future.

**Comment by gsmet** [comment]
@emmanuelbernard I think we should include the date in the URL.

Not exactly sure how to deal with the redirects for the existing entries though, I would need to check it's doable.

Would you be OK with the dates in the URL?

**Comment by maxandersen** [comment]
dates in urls are bad for SEO afaik and its ugly ;)  I would be -1 on adding date - I would rather just verify if any duplicate slugs.

Also how likely is it you have a duplicated filename ? :)

We could add some basic validation - like this will print which has duplicate "slugs":

```ls -1 | sed -e 's/....-..-..-\(.*\).adoc/\1/g' | sort | uniq -c | grep "^   2"```

**Comment by maxandersen** [comment]
5 years later and still no duplicates on same date...i think we'll survive :)
