### ISSUE TITLE
Linkable per-release docs

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkusio.github.io#268]
We started writing docs for Camel Quarkus where we will often refer to Quarkus documentation. Because every Camel Quarkus release depends on a specific Quarkus release, it would be handy to have per-release versions of Quarkus documentation with stable URLs.

**Comment by ppalaga** [comment]
I just noticed some versions already have per-release docs, e.g. https://quarkus.io/version/1.7/guides/ and https://quarkus.io/version/1.11/guides/ . I wonder what is the policy to select those versions that do have docs? There is no https://quarkus.io/version/1.10/guides or https://quarkus.io/version/1.12/guides

**Comment by ppalaga** [comment]
**sasas** sddsd

**Comment by ppalaga** [comment]
Closed by mistake, sorry

**Comment by maxandersen** [comment]
in general we keep one by active stream - so for LTS release and main.

reopen or open new if you think we need more explicit versions.
