### ISSUE TITLE
Contradictory statement about optimisation

### ISSUE THREAD

**Issue by nmcl** [quarkusio/quarkusio.github.io#274]
"Quarkus’s mission is to transform your entire application including the libraries it uses, into an artifact optimized for GraalVM."

from https://quarkus.io/guides/extension-authors-guide

We've always been very careful to state that GraalVM/SubstrateVM is an optional aspect of using Quarkus so to suggest otherwise needs re-thinking. Later on in the same page it (correctly) states "The Quarkus extension framework results in significantly improved resource utilization even when GraalVM is not used (e.g. in HotSpot)"

**Comment by gsmet** [comment]
Fixed in the main repo, will be deployed with the next release.
