### ISSUE TITLE
Add `https://code.quarkus.io/` to ways to start a project in getting-started-guide

### ISSUE THREAD

**Issue by abelsromero** [quarkusio/quarkusio.github.io#283]
I struggled to find the official generator, which I understand is `https://code.quarkus.io/`. I had to go through the twitter account to find the announcement.

For easy access, I'd be great to be added to:
* https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/getting-started-guide.adoc#4-bootstrapping-the-project as an alternative method.
or
* Some visible section in https://quarkus.io/get-started/. Maybe below "Guides" on the left, in a "Tools" section.

While searching I also found this issue which added more confusion to me. Is it still relevant? https://github.com/quarkusio/quarkus/issues/447

**Comment by cescoffier** [comment]
@abelsromero we are still working on the code generator. Once we are ready we will add the link and announce it officially.

**Comment by fbricon** [comment]
It's fixed in https://quarkus.io/get-started/ now:

<img width="688" alt="Screen Shot 2019-10-15 at 12 00 08 PM" src="https://user-images.githubusercontent.com/148698/66821841-681ba400-ef43-11e9-89fb-7ca06e4670d4.png">
