### ISSUE TITLE
Wrong option for start-tls at Sending Emails guide

### ISSUE THREAD

**Issue by lbernardomaia** [quarkusio/quarkusio.github.io#284]
Hi,

I tried to use the NONE option with start-tls and it doesn't work.  I had a look at the Vert.x documentation and the correct use is DISABLED instead of NONE, that doesn't exist.

https://vertx.io/docs/vertx-mail-client/java/
`startTLS StartTLSOptions either DISABLED, OPTIONAL or REQUIRED, default is OPTIONAL`

Thanks.

**Comment by gsmet** [comment]
Thanks for the report, I opened a PR here: https://github.com/quarkusio/quarkus/pull/3768 .
