### ISSUE TITLE
FAQ: Can I create a war file with Quarkus to be deployed to a MicroProfile application server such as WildFly, OpenLiberty, Payara, or TomEE? If not, why not?

### ISSUE THREAD

**Issue by pdurbin** [quarkusio/quarkusio.github.io#285]
Hi! Quarkus seems fantastic and I've gotten the "hello" example working on Mac, Ubuntu, and CentOS. I'm very excited about all of it, especially after attending a recent talk at DevConf and hearing about it a lot on the airhacks podcast. :smile: 

I'm coming from almost seven years of hacking on an open source Java EE application whereby we produce a war file for our customers. As of this writing we are using Java EE 7 and only support deployment of our war file to Glassfish. There are 46 installations worldwide and our app has been translated into 10 languages.

I assumed I'd be able to use Quarkus to create a war file but I don't believe this to be the case. There might be other people in my situation, people who are used to creating war files, so I'd like to propose a question in the Quarkus FAQ about this. I'd be happy to create a pull request to add this question but I'm blocked on understanding the "why" behind war files not being supported. This is what I have so far:

Q: Can I create a war file with Quarkus? If not, why not?

A: No, you cannot create a war file with Quarkus to be deployed to a MicroProfile application server such as WildFly, OpenLiberty, Payara, or TomEE. This is because...

Am I correct that I can't create a war file with Quarkus? If not, can you please tell me why not? Thanks!

**Comment by emmanuelbernard** [comment]
You are correct, you can't. Quarkus does not run inside a web server, it is its own web server. So running inside an app server does not make sense. MicroProfile is really one of the many APIs we offer to our users.

**Comment by emmanuelbernard** [comment]
I am not sure it warrants a FAQ, but I'll leave this one around in case others +1 that need.

**Comment by pdurbin** [comment]
@emmanuelbernard thanks for the reply.

Now that the talk by @danieloh30 that inspired me to install Quarkus is on YouTube, I can share a link: https://www.youtube.com/watch?v=k9P7p3HF72U

I guess what I'm trying to say is this:

Some teams have been building a war file for so long they may have come to think as that war file as the somewhat one and the same as their product. **Their product is the war file.** Quarkus is saying, "You shouldn't think of your product as a war file." Fine. But this might be a tough pill to swallow for some teams.

Let me know if you'd like to pick a time period for the +1's to come. I'm happy to close this issue now (or you can) if you feel like "no support for war files" is a non-issue.

p.s. Now we're up to 50 installations. 😄

**Comment by emmanuelbernard** [comment]
I felt that closing it would prevent the +1 dance so that's why I left it open. At least it's findable within the default search.

**Comment by pdurbin** [comment]
@emmanuelbernard that's cool. I'm kind of done with the +1 dance myself. For my open source project I'm playing around with having key stakeholders create their own boards (projects) under my GitHub org. I recently explained this in a talk for my community at https://scholar.harvard.edu/pdurbin/blog/2019/jupyter-notebooks-and-crazy-ideas-for-dataverse and later wrote a little script and explained it a little better (I hope) at "Use multiple GitHub Projects (boards) under an GitHub organization as data source for crowdsourced issue ordering" at https://github.com/pdurbin/druthers/issues/1

It sounds like you don't want anything about war files in the Quarkus FAQ without a certain number of +1s. That's fine with me. Closing.

**Comment by jspearo** [comment]
For us is important to have own code base that is possible build to many microservices to deploy to cloud, but for our customers that run app on-premise without kubernetes, we would like to assemble application to 1 ear or 1 runnable.
Without cloud environment and kubernetes, it is hardly to maintain many runnables (microservices).
Is there any solution for it?
