### ISSUE TITLE
404 link target on _guides/building-native-image-guide.adoc

### ISSUE THREAD

**Issue by lutzhorn** [quarkusio/quarkusio.github.io#288]
This line

```
NOTE: Interested by tiny Docker images, check the {quarkus-images-url}/graalvm-{graalvm-version}/distroless[distroless] version.
```

in `_guides/building-native-image-guide.adoc` generates a link tha results in a `404 Not Found` HTTP response:

https://github.com/quarkusio/quarkus-images/tree/graalvm-19.1.1/distroless

**Comment by gsmet** [comment]
@cescoffier any idea where we should point to?

**Comment by cescoffier** [comment]
I need to copy the old repo. Will do it tomorrow.

**Comment by cescoffier** [comment]
I knew I did it: https://github.com/quarkusio/quarkus-images/tree/master/distroless

**Comment by cescoffier** [comment]
Gonna fix the guide.

**Comment by cescoffier** [comment]
PR: https://github.com/quarkusio/quarkus/pull/3899

**Comment by maxandersen** [comment]
issue fixed in merge thus closing.
