### ISSUE TITLE
Couple more publications

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkusio.github.io#298]
hey @maxandersen 

could you add these for completeness please:

 - https://youtu.be/za5CSBX-UME is on youtube, my demo at Devoxx UK
 - https://www.heise.de/developer/artikel/Quarkus-Der-Blick-ueber-den-Tellerrand-4532556.html an extensive article by @michael-simons - in German though 

thanks!

**Comment by maxandersen** [comment]
yes, but is the devoxx UK video different enough from https://www.infoq.com/presentations/quarkus-graalvm-sao-paulo-2019/ that’s on the list ?  i.e. you want both or one instead of the other ?

**Comment by maxandersen** [comment]
watched most of it and its overlapping but slightly different so adding both - tell me if you prefer one of them removed ;)

german one is added now too. thanks.

**Comment by Sanne** [comment]
I'd suggest using the devoxx version as I feel I was slightly better
(maybe? It was later so I suppose I had more practice) But especially as I
think YouTube might be a better option for people to see it
