### ISSUE TITLE
Quarkus extensions for Camel is not listed

### ISSUE THREAD

**Issue by ravishankarhassain** [quarkusio/quarkusio.github.io#309]
Quarkus extensions for Apache Camel components is not listed in https://code.quarkus.io/ website 

In the camel github repo (https://github.com/apache/camel-quarkus/tree/master/extensions), I can see few Apache Camel extension for Quarkus but its not listed in the webpage

**Comment by maxandersen** [comment]
we are reworking how extensions are included; right now its limited to what is released together with quarkus - in next or next-next release we'll have ability to consume external extensions.
