### ISSUE TITLE
Link to the config property page not visible on mobile

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkusio.github.io#316]
https://quarkus.io/guides/all-config

is only int he guide menu which is not present in mobile

**Comment by FroMage** [comment]
Huh, I didn't even know we linked to it.

**Comment by FroMage** [comment]
So, I see it at the bottom of https://quarkus.io/guides/ but I feel it should sit either in /guides/application-configuration-guide or next to it in the list of guides. My preference is probably as a link from that /guides/application-configuration-guide page.

WDYT?

**Comment by FroMage** [comment]
So in my PR I've moved the guide link to the top right before the "how to configure" guide, and included a link in that guide too which should be visible enough since it has its own section. Does that fix your issue?

**Comment by emmanuelbernard** [comment]
👍

**Comment by FroMage** [comment]
Thanks.
