### ISSUE TITLE
Openshift Typos on https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/kubernetes-resources.adoc

### ISSUE THREAD

**Issue by akshakp** [quarkusio/quarkusio.github.io#324]
There are typos on https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/kubernetes-resources.adoc for Openshift as below highlighted (Under Openshift support section) :

> If you need to generate resources for both platforms (vanilla kubernetes and **opesnhift**), then you need to include both (coma separated).
> 
> kubernetes.deployment.target=kubernetes, openshift
> The **Openshfit** resources can be customized in a similar approach with kubernetes.
>

**Comment by gsmet** [comment]
This has been fixed.

**Comment by gsmet** [comment]
Thanks for the report.
