### ISSUE TITLE
Panache repository guide comes across as condescending....

### ISSUE THREAD

**Issue by InfoSec812** [quarkusio/quarkusio.github.io#326]
Using wording like "Look, we get it: you have a love/hate relationship with DAOs/Repositories but you can’t live without them. We don’t judge, we know life is tough and we’ve got you covered." and "We’re not judging" is off-putting and should probably be avoided. If you're "not judging", then it shouldn't sound like you're judging.

**Comment by gsmet** [comment]
So, for the record, I agree and I think we should be more neutral in our guides (both the original Panache one and the MongoDB Panache that got derived from it).

**Comment by FroMage** [comment]
It was meant to be funny. Obviously I'm biased so I'll let others decide.

**Comment by InfoSec812** [comment]
I would like to suggest something along the lines of:

> Repositories can be amazing or evil, depending on the complexity of your needs. When they work, they can save you from writing lots of boilerplate and error-prone JPA/SQL/Criteria queries, but when they fail you need a way to drop back to more traditional methods... Don't worry, Panache and Quarkus have you covered.

**Comment by machi1990** [comment]
@InfoSec812 if you would like to open a PR for the proposed change, it will be these two files that we'll have to modify:
 1. https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/hibernate-orm-panache-guide.adoc 
2. https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/mongodb-panache-guide.adoc

**Comment by InfoSec812** [comment]
Thanks Guillaume and Stuart!

Deven Phillips
Senior Consulting Engineer
Red Hat, Cloud Native AppDev Practice
