### ISSUE TITLE
Typo in homepage comic strip

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkusio.github.io#358]
Hi @jkbrock ,

In the first part of the comic strip https://quarkus.io/assets/images/homepage_comic_1.png , `java` should be `Java`.

Could you get this fixed?

Thanks!

**Comment by insectengine** [comment]
Typo corrected and Adela is merging it.

https://github.com/quarkusio/quarkusio.github.io/pull/375

**Comment by gsmet** [comment]
Thanks @insectengine !
