### ISSUE TITLE
Url for Intellij Idea download is not working

### ISSUE THREAD

**Issue by KaenDagger** [quarkusio/quarkusio.github.io#381]
https://github.com/quarkusio/quarkusio.github.io/blob/48a82943566ecd0ec9cbfdb5615a5a9419fd6897/_includes/get-started-band.html#L5

**Comment by gsmet** [comment]
Good catch! I added the fix to this ongoing PR: https://github.com/quarkusio/quarkusio.github.io/pull/379 that should be merged today.

**Comment by KaenDagger** [comment]
Okay I was about to make the PR for this fix. NP
