### ISSUE TITLE
Add Link to Video about Quarkus and GraalVM

### ISSUE THREAD

**Issue by predic8** [quarkusio/quarkusio.github.io#385]
Can you please add a link to my video about Quarkus as a fast Microservices Runtime to your list on:

https://quarkus.io/publications/

You can find the video at:

https://www.youtube.com/watch?v=L76_7qXeuTg&t=214s

The video shows that Quarkus, GraalVM and Docker are a great platform for developing and running fast and lightweight Microservices. (German Language!)
[Link: Quarkus, die schnellste Java Microservices Runtime für die Cloud? (German)] from predic8 by Thomas Bayer posted 21. Novemer 2019 on YouTube

**Comment by maxandersen** [comment]
thanks @predic8; just adding the necessary metadata here for when we do the next newsletter

```
- id: 14QuarkusdieschnellsteJavaMicroservicesRuntimefrdieCloudYouTube-2019-12-02
  type: video 
  title: "Quarkus, die schnellste Java Microservices Runtime für die Cloud?"
  date: "2019-11-21"
  author: "predic8"
  affiliation: "predic8"
  note: "Thomas shows that Quarkus, GraalVM and Docker are a great platform for developing and running fast and lightweight Microservices"
  url: "https://www.youtube.com/watch?v=L76_7qXeuTg"
  urldate: "2019-12-02"
  language: "de"
```
