### ISSUE TITLE
Mobile display is broken on most pages

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkusio.github.io#406]
I recorded a few screenshots of display problems on the mobile website. IMO those issues are really bad and should be taken seriously and treated as urgently as possible. The mobile design really needs more attention.

## Screen overflowing with a black background
![image](https://user-images.githubusercontent.com/2223984/71183200-d4828e80-2277-11ea-81a0-63861cea2db6.png)

## Lines going outside of the screen 
![image](https://user-images.githubusercontent.com/2223984/71183216-dd736000-2277-11ea-8e8c-d72fa1094dd4.png)

## Tables displaying really badly
![image](https://user-images.githubusercontent.com/2223984/71183320-14e20c80-2278-11ea-8ad1-aed3ce6de736.png)

I also noticed a scroll bar in the middle of the screen on some guides.

CC @jkbrock

**Comment by FroMage** [comment]
Also the guides page's TOC is absent on mobile, which makes the page unusable, as we can't navigate it.
