### ISSUE TITLE
provide documentation on readthedocs.org

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkusio.github.io#424]
Please provide **official quarkus documentation** on https://readthedocs.org/. It is free and has better navigation and usability than official quarkus documentation site. 

For example, look at the doc https://docs.godotengine.org/en/latest/ - the left panel with collapsable items in TOC and text search function. On the bottom right side of the left panel, you can click to show different versions and you can also download documents as pdf.

**Comment by maxandersen** [comment]
thanks for the suggestion! I agree we need to improve the doc navigation/overview but readthedocs.org does not support asciidoc thus there is very little point in trying to use their site to host our docs.
