### ISSUE TITLE
provide documentation at https://docs.jboss.org

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkusio.github.io#427]
Would be nice to provide quarkus site (documentation) also at https://docs.jboss.org/author/display/QUARKUS/ to have site structur similar to https://docs.jboss.org/author/display/WFLY/. From this site (at the top right corner->"Extras") we can also generate different output formats (html, pdf, ..). It supports ascidoctor by `asciidoctor-confluence` (https://github.com/asciidoctor/asciidoctor-confluence).

_See https://docs.jboss.org/author/display/AUTHGUIDE/How+to+create+and+manage+a+space._

**Comment by gsmet** [comment]
We don’t plan on doing that.

**Comment by gsmet** [comment]
We have plans to work on improving our documentation landing page but it will take some time.
