### ISSUE TITLE
Error in rest-client documentation 

### ISSUE THREAD

**Issue by r00ta** [quarkusio/quarkusio.github.io#437]
Hi, 

Following the documentation I found a little typo in the documentation of the page https://quarkus.io/guides/rest-client

In the entire document `@PathParam` is used without argument, like here 

```
@Path("/country")
public class CountriesResource {

    @Inject
    @RestClient
    CountriesService countriesService;


    @GET
    @Path("/name/{name}")
    @Produces(MediaType.APPLICATION_JSON)
    public Set<Country> name(@PathParam String name) {
        return countriesService.getByName(name);
    }
}
```

As you can see in the implementation of `PathParam`:
```
package org.jboss.resteasy.annotations.jaxrs;

..

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER})
public @interface PathParam {
    String value() default "";
}
```

the variable `name` will be `null`, i.e. the example is not working.

**Comment by gsmet** [comment]
No, it won't be null. If you have compiled with `-parameters` - which is the default if you have used our generator - it will use the name of the parameter in your code (provided you use the annotations from `org.jboss.resteasy.annotations.jaxrs`).

**Comment by r00ta** [comment]
Thank you @gsmet , I was running the tests directly from Intellij and it was not working. With `mvnw` it works as you pointed out. 

Best

**Comment by gsmet** [comment]
I’m pretty sure you can configure IntelliJ to compile with `-parameters` too.
