### ISSUE TITLE
Multiple extensions matching 'opentraicing'

### ISSUE THREAD

**Issue by wedamartinez** [quarkusio/quarkusio.github.io#442]
Error when you run the command that you find in the guide of opentracing https://quarkus.io/guides/opentracing 
```
mvn io.quarkus:quarkus-maven-plugin:1.2.0.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=config-quickstart \
    -DclassName="org.acme.config.GreetingResource" \
    -Dpath="/greeting"
cd config-quickstart
```

```
INFO] --- quarkus-maven-plugin:1.2.0.Final:create (default-cli) @ standalone-pom ---
Creating a new project in /Users/alex81sp/opentracing-quickstart
❌ Multiple extensions matching 'opentracing'
     * org.apache.camel.quarkus:camel-quarkus-opentracing
     * io.quarkus:quarkus-smallrye-opentracing
     Be more specific e.g using the exact name or the full GAV.
```
When I choose quarkus-smallrye-opentracing works correctly.

**Comment by gsmet** [comment]
This has already been fixed in master here: https://github.com/quarkusio/quarkus/pull/6874 .

I will publish it today.

**Comment by wedamartinez** [comment]
Thanks @gsmet ! and sorry, next time I will review the master branch before report the issue.

**Comment by gsmet** [comment]
No worries, it pushed me to update it now rather than in one month. It will be better for our next readers.

I just pushed the fix to the website.
