### ISSUE TITLE
Display blogs by tag (user stories)

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkusio.github.io#448]
Now that there are a  larger number of blogs, we need a way to display blog entries by tag. The immediate driver for this request is "I'd like to see who is using Quarkus". We have ~5 Quarkus user stories  (with more on the way), but I have to scroll through blog history to find them, and then paste 5 links in tweets or emails. I'd like to be able to paste a link to a tag that just displays the user stories.

Of course, this can be useful for other tags as well.

Order: Most recent first.

**Comment by maxandersen** [comment]
https://quarkus.io/blog/tag/user-story/ and similar is now live.

no links pointing to it though - that’s next step. but now you have a url to share.
