### ISSUE TITLE
Write samples about how to merge a Panache entity

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkusio.github.io#489]
In the Panache guide (https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/hibernate-orm-panache.adoc) there is no example on how to merge a detached Panache entity. 

I was expecting to have a `merge()` (or `saveOrUpdate`) method so I could attach a detached entity, something like that:

```
@Transactional(REQUIRED)
public class BookService {

  public Book updateBook(@Valid Book book) {
    return Book.merge(book); 
  }
}
```

The only reference to updating in the guide is `Person.update` passing a query, which is not the use case of merging.

Could you explain and write an example on how to merge a detached Panache entity ?
Thanks

**Comment by DonaldMaparura** [comment]
hi....... 
Did you find answer to this question im facing the same challenge

**Comment by agoncal** [comment]
Looks like the `merge` won't happen. In the meantime what you can do is `Panache.getEntityManager().merge()`

**Comment by DonaldMaparura** [comment]
ok thanks my guy

**Comment by DonaldMaparura** [comment]
it really did the trick l have been going round all afternoon thanks a
lot..........if you are ok with me asking another error im facing
