### ISSUE TITLE
whats new in metrics

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkusio.github.io#578]
What default metrics do we have, how to use them and how does users add their own
+ 1.8 on micrometer support and how it relate to MP metrics.

**Comment by maxandersen** [comment]
scheduled for monday 14th september, guests @kenfinnigan and @ebullient

**Comment by ebullient** [comment]
How much are you expecting me to dance around the issues with MP Metrics.
I'll have to work at it.
