### ISSUE TITLE
Do a Quarkus insights about  Quarkus jHipster

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkusio.github.io#590]
- what is jhipster
- what kind of app is it building
- demo
- discuss various options
- show the end result usage
- show the code

**Comment by emmanuelbernard** [comment]
Proposed outline by Daniel

What is JHipster
Full Stack App generator historically based on Spring
What is a "Blueprint": override the generation stages to permit new implementation like Java -> Kotlin/dotnet/JS, Spring -> Quarkus
What it's interesting: the usual stuff like App density, resources/financial optimization
Demo:
How to install it
How to create an app + quick tour of what's generated, the 2/3 notesworthy stuff (like authentication, Qute, Panache usage)
How to create an entity + quicktour : Active Record vs Repository, validation, Pagination, tests
JVM packaging, just to show that everything is bundled (back and front) but I won't spot the startup time because liquibase is killing the waouh effect (7s to start)
(optional) Jhipster Domain Language: how to generate a full app from a DSL
Going native. I would prepare an executable otherwise it's 5-8min build... not very sexy. The objective is to show the startup time and memory
Conclusion:
Doc, support etc
Project roadmap, ambition
Sounds good?

**Comment by maxandersen** [comment]
completed with quarkus insights #4 https://www.youtube.com/watch?v=MJe2giXrbuM
