### ISSUE TITLE
Quote block's text is white on a gray background

### ISSUE THREAD

**Issue by dmi3coder** [quarkusio/quarkusio.github.io#625]
Example https://quarkus.io/guides/microprofile-graphql

It would be great to make font either dark-gray or some light-blue maybe. I assume it's set by default from outer styles, I couldn't find any color styles for quote-block.
![image](https://user-images.githubusercontent.com/12466860/83939549-8db53080-a7e6-11ea-9a3f-8b04368deb5e.png)

**Comment by emmanuelbernard** [comment]
Thanks, I created https://issues.redhat.com/browse/DESIGN-1959 for the designers taking care of the website to find the best solution.

**Comment by emmanuelbernard** [comment]
A fix has bee applied by Guillaume.
