### ISSUE TITLE
OpenApi Guide Add-Extension Doesn't Work

### ISSUE THREAD

**Issue by raffamendes** [quarkusio/quarkusio.github.io#626]
When running the command from the guide

```
./mvnw quarkus:add-extension -Dextensions="openapi"
```
I got the following error:

![image](https://user-images.githubusercontent.com/54948088/83958232-dfd96e80-a845-11ea-93ce-e2bc122cd2ea.png)

I'll submit a pull request with the correct command.
```
./mvnw quarkus:add-extension -Dextensions="quarkus-smallrye-openapi"
```

**Comment by emmanuelbernard** [comment]
Applied on website and quarkus master.
