### ISSUE TITLE
Typo of Amazon Lambas in the left menu

### ISSUE THREAD

**Issue by danieloh30** [quarkusio/quarkusio.github.io#644]
2 typos are founded in https://quarkus.io/guides/

- Quarkus Funqy Amazon Lambas
- Quarkus Funqy Amazon Lambas HTTP

"Lambas" should be rectified to "Lambdas".

**Comment by gsmet** [comment]
Thanks for taking the time to report it! I pushed a fix, it should be deployed in a few minutes.
