### ISSUE TITLE
Issue in docs

### ISSUE THREAD

**Issue by dodalovic** [quarkusio/quarkusio.github.io#647]
When reading this [guide](https://quarkus.io/guides/getting-started), there's compilation error:

![image](https://user-images.githubusercontent.com/6358061/86334278-4edf9280-bc4d-11ea-9073-a4175b6520c6.png)

Probably `rs` API has changed in the meantime.

**Comment by gsmet** [comment]
Are you sure you got the imports right?

The import `import org.jboss.resteasy.annotations.jaxrs.PathParam;` is just above.

**Comment by dodalovic** [comment]
My bad, my apology :disappointed:

**Comment by gsmet** [comment]
No worries, it's a bit confusing. Hopefully, at some point the JAX-RS annotations will be adjusted.
