### ISSUE TITLE
`quarkus-bom-deployment` not found for 1.7.0 Release

### ISSUE THREAD

**Issue by raptium** [quarkusio/quarkusio.github.io#703]
The [Building My First Extension](https://quarkus.io/guides/building-my-first-extension) guide says I need to import `io.quarkus:quarkus-bom-deployment` in my extension, however there is no `quarkus-bom-deployment` any more for 1.7.0. What bom artifact should I use for dependency management?

**Comment by gastaldi** [comment]
Looks like this is already fixed. Closing
