### ISSUE TITLE
Wrong image src in quarkus.io/guides/scripting 

### ISSUE THREAD

**Issue by alex81sp** [quarkusio/quarkusio.github.io#731]
In https://quarkus.io/guides/scripting image `getting-started-architecture.png` source is not correct.

`<img src="getting-started-architecture.png" alt="Architecture">`
should be  
`<img src="images/getting-started-architecture.png" alt="Architecture">`

I guess the conversion from asciidoc had a problem, because the `scripting.adoc` file is correct 

@gsmet

**Comment by gsmet** [comment]
Yeah it got fixed yesterday by @abelsromero and merged today.

I will push it manually without waiting for the next micro release as it seems a lot of people are noticing.

**Comment by gsmet** [comment]
Done. Thanks for opening an issue.

**Comment by alex81sp** [comment]
Thank you to you!
