### ISSUE TITLE
Add Quarkus books

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkusio.github.io#783]
- [Practising Quarkus](https://developers.redhat.com/books/practising-quarkus)
- [Understanding Quarkus](https://developers.redhat.com/books/understanding-quarkus)
- [Kubernetes Native Microservices with MicroProfile and Quarkus](https://www.manning.com/books/kubernetes-native-microservices-with-quarkus-and-microprofile)

**Comment by gastaldi** [comment]
The first two were added in https://github.com/quarkusio/quarkusio.github.io/commit/691c03b5498d0a58bbc6b7834ee2ef28bbf74877
