### ISSUE TITLE
I found a suspicious looking website quarkus.pro

### ISSUE THREAD

**Issue by joern19** [quarkusio/quarkusio.github.io#818]
I found some Chinese Text on the bottom of the Page: https://quarkus.pro/guides/context-propagation.html

Is it possible to just claim the domain to prevent any further confusion?

**Comment by maxandersen** [comment]
claiming domains and Chinese laws are trick. we've asked the owner to make it clearer it is not official quarkus and there is not top and bottom texts for this.

In addition we now have https://cn.quarkus.io as official community backed (simple) chinese translations.
