### ISSUE TITLE
Vert.x tag results in 404 page

### ISSUE THREAD

**Issue by glefloch** [quarkusio/quarkusio.github.io#821]
When trying to access `https://quarkus.io/blog/tag/vert.x` (from the tag list), it ends in 404 whereas there is at least one article with this tag: https://quarkus.io/blog/mutiny-vertx/

**Comment by gsmet** [comment]
Wouldn't be surprised if it's due to the `.`.

**Comment by glefloch** [comment]
The funny things is that replacing the `.` by `-` works `https://quarkus.io/blog/tag/vert-x/`.

**Comment by emmanuelbernard** [comment]
I thought I had opened the issue, but I think our process for tag used for the URL and the URL build for the tag cloud is different. We had another case like that (case sensitivity related).

**Comment by gsmet** [comment]
Yeah I improved things here: https://github.com/quarkusio/quarkusio.github.io/pull/824 .

Hopefully, it will catch most of the mismatches.

**Comment by glefloch** [comment]
Closing this one as #824 fix the issue.
