### ISSUE TITLE
QUARKUS - DEPLOYING ON OPENSHIFT - image tag incorrect

### ISSUE THREAD

**Issue by magreenberg** [quarkusio/quarkusio.github.io#842]
Follow the directions on the [QUARKUS - DEPLOYING ON OPENSHIFT](https://quarkus.io/guides/deploying-to-openshift) page.
After building the image run:
```bash
oc get is
```
The image has a tag of:
```
1.0.0-SNAPSHOT
```
Whereas the instructions to run the image use tag:
```
1.0-SNAPSHOT
```
The instructions needs to be changed to match the generated tag.

**Comment by gsmet** [comment]
Thanks, I created https://github.com/quarkusio/quarkus/pull/14568 to fix it.

It will be fixed for the next release!
