### ISSUE TITLE
Missing Infinispan logo in section "Best of Breeds Libraries and Standards"

### ISSUE THREAD

**Issue by cealsair** [quarkusio/quarkusio.github.io#92]
Please add the infinispan logo to the section mentioned in the subject line. Infinispan logo can be found here:
http://design.jboss.org/infinispan/

and here's the 600px one:
http://design.jboss.org/infinispan/logo/images/infinispan_logo_600px.svg

Thanks,
Cesar

**Comment by gsmet** [comment]
It has been fixed a long time ago.
