### ISSUE TITLE
The All Config page is incredibly slow

### ISSUE THREAD

**Issue by richiethom** [quarkusio/quarkusio.github.io#941]
## Describe the bug
https://quarkus.io/guides/all-config is incredibly slow to load.

### Expected behavior
A page that loads quickly that I can then filter/search.

### Actual behavior
A  page that loads very slowly, sometimes not at all. If it does load, then the results are still search/filterable.

**Comment by mkouba** [comment]
It seems that a great deal of time is spent in the `config.js`, namely when iterating over the nodes with CSS class `description` (more than 2500 occurrences): https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/javascript/config.js#L24-L26

**Comment by mkouba** [comment]
I think that we can close this one. The page loads reasonably fast now.
