### ISSUE TITLE
Footnotes substantially affect list spacing

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkusio.github.io#96]
![screen shot 2019-03-06 at 11 39 39 pm](https://user-images.githubusercontent.com/124581/53919088-323b4680-4069-11e9-8928-60187d622cce.png)

Ideally the footnote would not cause a variation in line spacing.

**Comment by gsmet** [comment]
Looks like we got rid of the foot note. Let's say it's a fix :).
