### ISSUE TITLE
Qute guid uses @ResourcePath

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkusio.github.io#966]
**Describe the bug**
`@ResourcePath` seems to be deprecated by `@Location`

**Which pages**
https://quarkus.io/guides/qute

Moved from https://github.com/quarkusio/quarkus-quickstarts/issues/843

**Comment by mkouba** [comment]
@rvansa You're too fast ;-). I just wanted to mention that this is already fixed in the main branch: https://github.com/quarkusio/quarkus/commit/65491bcf3a6525e0acfd831d2f1d020250665b09.
